// src/lib/ui/SpriteSelector.svelte
<script lang="ts">
	import { getRPGMaker } from '../../rpgmaker';
	import type { IActor } from '../../rpgmaker/declare';

	interface Props {
		type?: 'alias' | 'enemy';
		all?: boolean;
		alive?: boolean;
		value?: number;
		actors?: IActor[];
	}

	let {
		type = 'alias',
		all = false,
		alive = false,
		value = $bindable(0),
		actors = $bindable([])
	}: Props = $props();

	let label: string = $derived(type === 'alias' ? 'Aliases' : 'Enemies');

	$effect(() => {
		try {
			if (type === 'alias') {
				actors = getRPGMaker().getAliasList();
			} else {
				actors = getRPGMaker().getEnemyList();
			}
		} catch (e) {
			console.error(e);
		}
	});
</script>

<select bind:value={value}>
	{#if alive}
		<option value={-2}>Alive {label}</option>
	{/if}
	{#if all}
		<option value={-1}>All {label}</option>
	{/if}
	{#each actors as actor (actor.id)}
		<option value={actor.id}>{actor.id}: {actor.name || '-'}</option>
	{/each}
</select>

// src/component/SpriteSelector/index.tsx
import { ReactElement, useMemo } from "react";
import { getRPGMaker } from "../../rpgmaker";
import { IActor, TeamType } from "../../rpgmaker/declare";

export type Value = IActor["id"] | "all" | "alive";

export interface ISpriteSelectorProps {
  teamType: TeamType;
  value?: Value;
  onChange?: (value: Value) => void;
  all?: boolean;
  alive?: boolean;
}

export default function SpriteSelector({
  all,
  alive,
  teamType,
  value,
  onChange,
}: ISpriteSelectorProps): ReactElement {
  const actors = useMemo(() => {
    if (teamType === "alias") {
      return getRPGMaker().getAliasList();
    }
    return getRPGMaker().getEnemyList();
  }, []);
  const label = useMemo(
    () => (teamType === "alias" ? "Aliases" : "Enemies"),
    [teamType],
  );
  return (
    <select value={value} onChange={(e) => onChange?.(e.target.value as Value)}>
      {all && <option value="all">All {label}</option>}
      {alive && <option value="alive">Alive {label}</option>}
      {actors.map((a, i) => (
        <option key={i} value={`${a.id}`}>
          {a.name}
        </option>
      ))}
    </select>
  );
}
