// src/lib/module/chronus/ChronusTimeHack.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { MakeScriptEventName } from '../../../config/event';
	import { getRPGMaker } from '../../../rpgmaker';
	import type { Script } from '../../../rpgmaker/declare';
	import FormItemWithButton from '../../ui/FormItemWithButton.svelte';
	import { DefaultValue, type IChronusTimeHackValue } from '../DefaultValue';

	interface Props {
		value?: ReturnType<IChronusTimeHackValue['ChronusTimeHack']>;
		script?: Script;
	}

	let { value = $bindable(DefaultValue.ChronusTimeHack()), script = $bindable('') }: Props = $props();

	const maker = getRPGMaker();

	function make() {
		script = `$gameSystem.chronus().addTime(${value});`;
		return script;
	}

	function run() {
		maker.evaluate(make());
	}

	onMount(() => {
		window.addEventListener(MakeScriptEventName, make);
		return () => {
			window.removeEventListener(MakeScriptEventName, make);
			make();
		};
	});
</script>


<FormItemWithButton onclick={run}>
	<input placeholder="In minutes" type="number" step="60" bind:value={value}>
	{#snippet button()}
		<span>{value < 0 ? '-' : '+'}</span>
	{/snippet}
</FormItemWithButton>

// src/component/module/chronus/ChronusTimeHack/index.tsx
import { useProxy } from "@allape/use-loading";
import { ReactElement, useCallback, useEffect } from "react";
import { getRPGMaker } from "../../../../rpgmaker";
import { ICheatModuleProps } from "../../declare";
import styles from "./style.module.scss";

export default function ChronusTimeHack({
  value,
  onChange,
  onScriptChange,
}: ICheatModuleProps): ReactElement {
  const [v, vRef, setV] = useProxy<number>(60);

  const make = useCallback(() => {
    return `$gameSystem.chronus().addTime(${vRef.current});`;
  }, [vRef]);

  const run = useCallback(() => {
    getRPGMaker().evaluate(make());
  }, [make]);

  useEffect(() => {
    if (value) {
      setV((v) => parseInt(value) || v);
    }
  }, [setV, value]);

  useEffect(() => {
    return () => {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      onChange?.(`${vRef.current}`);
      onScriptChange?.(make());
    };
  }, [make, onChange, onScriptChange, vRef]);

  return (
    <div className={styles.wrapper}>
      <input
        type="number"
        placeholder="In Minutes"
        step="60"
        min={0}
        value={v}
        onChange={(e) => setV(parseInt(e.target.value))}
      />
      <button onClick={run}>{v <= 0 ? "-" : "+"}</button>
    </div>
  );
}
