// src/component/module/DevTools/index.tsx
import { ReactElement, useCallback, useEffect } from "react";
import { getRPGMaker } from "../../../rpgmaker";
import { ICheatModuleProps } from "../declare";

export default function DevTools({
  onScriptChange,
}: ICheatModuleProps): ReactElement {
  const make = useCallback(
    () => getRPGMaker().getScriptGenerator().openDevTools(),
    [],
  );

  const run = useCallback(() => {
    getRPGMaker().evaluate(make());
  }, [make]);

  useEffect(() => {
    return () => {
      onScriptChange?.(make());
    };
  }, [make, onScriptChange]);

  return (
    <button style={{ flex: 1 }} onClick={run}>
      Open DevTools
    </button>
  );
}

// src/lib/module/DevTools.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getRPGMaker } from '../../rpgmaker';
	import type { Script } from '../../rpgmaker/declare';

	// export let value: string = '';
	export let script: Script = '';

	const maker = getRPGMaker();

	function make() {
		return maker.getScriptGenerator().openDevTools();
	}

	function run() {
		maker.evaluate(make());
	}

	onMount(() => {
		return () => {
			script = make();
		};
	});
</script>

<button on:click={run}>Open Dev Tools</button>
