// src/component/module/Gold/index.tsx
import { useProxy } from "@allape/use-loading";
import { ReactElement, useCallback, useEffect } from "react";
import { getRPGMaker } from "../../../rpgmaker";
import { ICheatModuleProps } from "../declare";
import styles from "./style.module.scss";

export default function Gold({
  value,
  onChange,
  onScriptChange,
}: ICheatModuleProps): ReactElement {
  const [v, vRef, setV] = useProxy<number>(10_000);

  const make = useCallback(() => {
    return getRPGMaker().getScriptGenerator().gainGold(vRef.current);
  }, [vRef]);

  const run = useCallback(() => {
    getRPGMaker().evaluate(make());
  }, [make]);

  useEffect(() => {
    if (value) {
      setV((v) => parseInt(value) || v);
    }
  }, [setV, value]);

  useEffect(() => {
    return () => {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      onChange?.(`${vRef.current}`);
      onScriptChange?.(make());
    };
  }, [make, onChange, onScriptChange, vRef]);

  return (
    <div className={styles.wrapper}>
      <input
        type="number"
        step="10000"
        value={v}
        onChange={(e) => setV(parseInt(e.target.value))}
      />
      <button onClick={run}>
        {v <= 0 ? "-" : "+"} <br />{" "}
        <span style={{ color: "orange" }}>Gold</span>
      </button>
    </div>
  );
}

// src/lib/module/Gold.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getRPGMaker } from '../../rpgmaker';
	import type { Script } from '../../rpgmaker/declare';
	import FormItemWithButton from '../ui/FormItemWithButton.svelte';

	export let value: number = 0;
	export let script: Script = '';

	const maker = getRPGMaker();

	function make() {
		return maker.getScriptGenerator().gainGold(value);
	}

	function run() {
		maker.evaluate(make());
	}

	onMount(() => {
		return () => {
			script = make();
		};
	});
</script>


<FormItemWithButton on:click={run}>
	<input placeholder="Gold! The Gold!!!" type="number" step="1" bind:value={value}>
	<span slot="button">{value < 0 ? '-' : '+'}</span>
</FormItemWithButton>
