// src/component/module/Save/index.tsx
import { useProxy } from "@allape/use-loading";
import { ReactElement, useCallback, useEffect } from "react";
import { getRPGMaker } from "../../../rpgmaker";
import { ICheatModuleProps } from "../declare";
import styles from "./style.module.scss";

export default function Save({
  value,
  onChange,
  onScriptChange,
}: ICheatModuleProps): ReactElement {
  const [v, vRef, setV] = useProxy<number>(2);

  const make = useCallback(() => {
    return getRPGMaker()
      .getScriptGenerator()
      .saveGame(vRef.current >> 0);
  }, [vRef]);

  const run = useCallback(() => {
    getRPGMaker().evaluate(make());
  }, [make]);

  useEffect(() => {
    if (value) {
      setV((v) => parseInt(value) || v);
    }
  }, [setV, value]);

  useEffect(() => {
    return () => {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      onChange?.(`${vRef.current}`);
      onScriptChange?.(make());
    };
  }, [make, onChange, onScriptChange, vRef]);

  return (
    <div className={styles.wrapper}>
      <input
        type="number"
        step="1"
        min={0}
        value={v}
        onChange={(e) => setV(parseInt(e.target.value))}
      />
      <button onClick={run}>
        Save <br /> Now
      </button>
    </div>
  );
}

// src/lib/module/Save.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getRPGMaker } from '../../rpgmaker';
	import type { Script } from '../../rpgmaker/declare';
	import FormItemWithButton from '../ui/FormItemWithButton.svelte';

	export let value: number = 2;
	export let script: Script = '';

	const maker = getRPGMaker();

	function make(): Script {
		return maker.getScriptGenerator().saveGame(Number(value));
	}

	function run(): void {
		maker.evaluate(make());
	}

	onMount(() => {
		return () => {
			script = make();
		};
	});
</script>

<FormItemWithButton on:click={run}>
	<input placeholder="Slot index" min="1" max="99" type="number" bind:value={value}>
	<span slot="button">Save Now</span>
</FormItemWithButton>
