// src/component/module/SpeedHack/index.tsx
import { useProxy } from "@allape/use-loading";
import { ReactElement, useCallback, useEffect } from "react";
import { getRPGMaker } from "../../../rpgmaker";
import { ICheatModuleProps } from "../declare";
import styles from "./style.module.scss";

export default function SpeedHack({
  value,
  onChange,
  onScriptChange,
}: ICheatModuleProps): ReactElement {
  const [v, vRef, setV] = useProxy<number>(0);

  const make = useCallback(() => {
    return getRPGMaker()
      .getScriptGenerator()
      .speedHack(vRef.current * 60);
  }, [vRef]);

  const run = useCallback(() => {
    getRPGMaker().evaluate(make());
  }, [make]);

  useEffect(() => {
    if (value) {
      setV((v) => parseInt(value) || v);
    }
  }, [setV, value]);

  useEffect(() => {
    return () => {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      onChange?.(`${vRef.current}`);
      onScriptChange?.(make());
    };
  }, [make, onChange, onScriptChange, vRef]);

  return (
    <div
      className={styles.wrapper}
      title={"Warning: High speed may cause game to crash"}
    >
      <input
        type="range"
        min="0"
        max="5"
        step="1"
        value={v}
        onChange={(e) => setV(+e.target.value)}
      />
      <button onClick={run}>
        {v}x <br /> Faster
      </button>
    </div>
  );
}

// src/lib/module/SpeedHack.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getRPGMaker } from '../../rpgmaker';
	import type { Script } from '../../rpgmaker/declare';
	import FormItemWithButton from '../ui/FormItemWithButton.svelte';

	export let value: number = 0;
	export let script: Script = '';

	const maker = getRPGMaker();

	function make(): Script {
		return maker.getScriptGenerator().speedHack(value * 60);
	}

	function run(): void {
		maker.evaluate(make());
	}

	onMount(() => {
		return () => {
			script = make();
		};
	});
</script>


<FormItemWithButton on:click={run}>
	<input type="range" min="0" max="3" step="1" bind:value={value}>
	<span slot="button">Hack</span>
</FormItemWithButton>
