// src/lib/ui/MapSelector.svelte
<script lang="ts">
	import { getRPGMaker } from '../../rpgmaker';
	import type { IMap } from '../../rpgmaker/declare';

	export let value: IMap['id'] = -1;
	export let readonly: boolean = false;

	export let maps = getRPGMaker().getMapList();
</script>

<select bind:value={value} disabled={readonly}>
	{#each maps as map (map.id)}
		<option value={map.id}>{map.id}: {map?.name || '-'}</option>
	{/each}
</select>

// src/component/MapSelector/index.tsx
import { HTMLProps, ReactElement, useMemo } from "react";
import { getRPGMaker } from "../../rpgmaker";
import { IMap } from "../../rpgmaker/declare";

export interface IMapSelectorProps
  extends Omit<HTMLProps<HTMLSelectElement>, "value" | "onChange"> {
  value?: IMap["id"];
  onChange?: (value: IMap["id"]) => void;
}

export default function MapSelector({
  value,
  onChange,
  ...props
}: IMapSelectorProps): ReactElement {
  const maps = useMemo(() => getRPGMaker().getMapList(), []);
  return (
    <select
      {...props}
      value={value}
      onChange={(e) => onChange?.(+e.target.value)}
    >
      {maps.map((m) => (
        <option key={m.id} value={m.id}>
          {m.name}
        </option>
      ))}
    </select>
  );
}
