// src/lib/ui/KeyBinder.svelte
<script lang="ts">
	interface Props {
		key?: string;
	}

	let { key = $bindable('') }: Props = $props();

	let binding: boolean = $state(false);

	function handleKeyUp(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			key = '';
		} else {
			key = e.key;
		}
		handleCancel();
	}

	function handleClick() {
		handleCancel();
		binding = true;
		window.addEventListener('keyup', handleKeyUp);
	}

	function handleCancel() {
		binding = false;
		window.removeEventListener('keyup', handleKeyUp);
	}

</script>

<style lang="scss">
  .wrapper {
    width: 100%;
    white-space: none;
    text-align: center;

    &.binding {
      cursor: wait;
    }
  }
</style>

<button class="wrapper" class:binding={binding} title={`Keyboard hot key [${key}]`} onclick={handleClick}
				onpointerleave={handleCancel}
				onblur={handleCancel}>
	{#if binding}
		[Esc] to clear, wait...
	{:else}
		{#if key}
			[{key}]
		{:else}
			Click to bind a hot key
		{/if}
	{/if}
</button>

// src/view/Form/component/KeyBinder/index.tsx
import { useProxy } from "@allape/use-loading";
import { KeyboardEvent, ReactElement, useCallback } from "react";

export interface IKeyBinderProps {
  value?: string;
  onChange?: (value: string) => void;
}

export default function KeyBinder({
  value,
  onChange,
}: IKeyBinderProps): ReactElement {
  const [binding, bindingRef, setBinding] = useProxy<boolean>(false);

  const handleClick = useCallback(() => {
    setBinding(true);
  }, [setBinding]);

  const handleCancel = useCallback(() => {
    setBinding(false);
  }, [setBinding]);

  const handleKeyUp = useCallback(
    (e: KeyboardEvent<HTMLButtonElement>) => {
      if (!bindingRef.current) {
        return;
      }
      setBinding(false);
      onChange?.(e.key);
    },
    [bindingRef, onChange, setBinding],
  );

  return (
    <button
      className="wrapper"
      title={`Keyboard key [${value}]`}
      onClick={handleClick}
      onPointerLeave={handleCancel}
      onBlur={handleCancel}
      onKeyUp={handleKeyUp}
    >
      {binding
        ? "[Esc] to clear, wait..."
        : value
          ? `[ ${value} ]`
          : "Click to bind a key"}
    </button>
  );
}
